# Generated by Django 5.1.4 on 2024-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Added/Created"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="Movie Description"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.CharField(max_length=50, verbose_name="Movie Picture"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Movie Name"),
        ),
    ]
