# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnFavori = QtWidgets.QPushButton(self.centralwidget)
        self.btnFavori.setGeometry(QtCore.QRect(50, 210, 301, 41))
        self.btnFavori.setObjectName("btnFavori")
        self.lbl_resteams = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resteams.setGeometry(QtCore.QRect(470, 50, 221, 161))
        self.lbl_resteams.setText("")
        self.lbl_resteams.setObjectName("lbl_resteams")
        self.groupTeams = QtWidgets.QGroupBox(self.centralwidget)
        self.groupTeams.setGeometry(QtCore.QRect(50, 20, 211, 181))
        self.groupTeams.setObjectName("groupTeams")
        self.widget = QtWidgets.QWidget(self.groupTeams)
        self.widget.setGeometry(QtCore.QRect(20, 30, 171, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbVkf = QtWidgets.QCheckBox(self.widget)
        self.cbVkf.setObjectName("cbVkf")
        self.verticalLayout.addWidget(self.cbVkf)
        self.cbEcz = QtWidgets.QCheckBox(self.widget)
        self.cbEcz.setObjectName("cbEcz")
        self.verticalLayout.addWidget(self.cbEcz)
        self.cbFB = QtWidgets.QCheckBox(self.widget)
        self.cbFB.setObjectName("cbFB")
        self.verticalLayout.addWidget(self.cbFB)
        self.groupLangs = QtWidgets.QGroupBox(self.centralwidget)
        self.groupLangs.setGeometry(QtCore.QRect(50, 260, 201, 181))
        self.groupLangs.setObjectName("groupLangs")
        self.layoutWidget = QtWidgets.QWidget(self.groupLangs)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 171, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbRust = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbRust.setObjectName("cbRust")
        self.verticalLayout_2.addWidget(self.cbRust)
        self.cbGo = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbGo.setObjectName("cbGo")
        self.verticalLayout_2.addWidget(self.cbGo)
        self.cbPy = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbPy.setObjectName("cbPy")
        self.verticalLayout_2.addWidget(self.cbPy)
        self.btnDilFavori = QtWidgets.QPushButton(self.centralwidget)
        self.btnDilFavori.setGeometry(QtCore.QRect(50, 450, 301, 41))
        self.btnDilFavori.setObjectName("btnDilFavori")
        self.lbl_reslangs = QtWidgets.QLabel(self.centralwidget)
        self.lbl_reslangs.setGeometry(QtCore.QRect(475, 297, 191, 141))
        self.lbl_reslangs.setText("")
        self.lbl_reslangs.setObjectName("lbl_reslangs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnFavori.setText(_translate("MainWindow", "Favori Takımını Seç"))
        self.groupTeams.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbVkf.setText(_translate("MainWindow", "Vakıfbank"))
        self.cbEcz.setText(_translate("MainWindow", "Eczacıbaşı"))
        self.cbFB.setText(_translate("MainWindow", "Fenerbahçe"))
        self.groupLangs.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbRust.setText(_translate("MainWindow", "Rust"))
        self.cbGo.setText(_translate("MainWindow", "Go"))
        self.cbPy.setText(_translate("MainWindow", "Python"))
        self.btnDilFavori.setText(_translate("MainWindow", "Favori Dilini Seç"))
