# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_combobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupCities = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCities.setGeometry(QtCore.QRect(10, 0, 921, 561))
        self.groupCities.setObjectName("groupCities")
        self.btn_clearitems = QtWidgets.QPushButton(self.groupCities)
        self.btn_clearitems.setGeometry(QtCore.QRect(100, 340, 751, 61))
        self.btn_clearitems.setObjectName("btn_clearitems")
        self.lbl_res = QtWidgets.QLabel(self.groupCities)
        self.lbl_res.setGeometry(QtCore.QRect(500, 50, 321, 111))
        self.lbl_res.setText("")
        self.lbl_res.setObjectName("lbl_res")
        self.btn_getitem = QtWidgets.QPushButton(self.groupCities)
        self.btn_getitem.setGeometry(QtCore.QRect(90, 250, 371, 51))
        self.btn_getitem.setObjectName("btn_getitem")
        self.btn_loaditems = QtWidgets.QPushButton(self.groupCities)
        self.btn_loaditems.setGeometry(QtCore.QRect(480, 250, 371, 51))
        self.btn_loaditems.setObjectName("btn_loaditems")
        self.cbCities = QtWidgets.QComboBox(self.groupCities)
        self.cbCities.setGeometry(QtCore.QRect(90, 50, 381, 111))
        self.cbCities.setObjectName("cbCities")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupCities.setTitle(_translate("MainWindow", "GroupBox"))
        self.btn_clearitems.setText(_translate("MainWindow", "Clear Items"))
        self.btn_getitem.setText(_translate("MainWindow", "Get Item"))
        self.btn_loaditems.setText(_translate("MainWindow", "Load Items"))
