# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_datetime.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.date_start = QtWidgets.QDateEdit(self.centralwidget)
        self.date_start.setGeometry(QtCore.QRect(50, 170, 331, 91))
        self.date_start.setObjectName("date_start")
        self.date_time = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.date_time.setGeometry(QtCore.QRect(50, 320, 331, 91))
        self.date_time.setObjectName("date_time")
        self.date_finish = QtWidgets.QDateEdit(self.centralwidget)
        self.date_finish.setGeometry(QtCore.QRect(440, 170, 331, 91))
        self.date_finish.setObjectName("date_finish")
        self.btn_calc_time = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calc_time.setGeometry(QtCore.QRect(450, 320, 141, 71))
        self.btn_calc_time.setObjectName("btn_calc_time")
        self.btn_calc_date = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calc_date.setGeometry(QtCore.QRect(610, 320, 141, 71))
        self.btn_calc_date.setObjectName("btn_calc_date")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 30, 721, 121))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.time_start = QtWidgets.QTimeEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_start.sizePolicy().hasHeightForWidth())
        self.time_start.setSizePolicy(sizePolicy)
        self.time_start.setObjectName("time_start")
        self.horizontalLayout.addWidget(self.time_start)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.time_finish = QtWidgets.QTimeEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_finish.sizePolicy().hasHeightForWidth())
        self.time_finish.setSizePolicy(sizePolicy)
        self.time_finish.setObjectName("time_finish")
        self.horizontalLayout.addWidget(self.time_finish)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_calc_time.setText(_translate("MainWindow", "Calculate Time"))
        self.btn_calc_date.setText(_translate("MainWindow", "Calculate Date"))
