# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 738)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.products_table = QtWidgets.QTableWidget(self.centralwidget)
        self.products_table.setGeometry(QtCore.QRect(20, 20, 591, 311))
        self.products_table.setObjectName("products_table")
        self.products_table.setColumnCount(0)
        self.products_table.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(630, 20, 241, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.product_name_text = QtWidgets.QLabel(self.formLayoutWidget)
        self.product_name_text.setObjectName("product_name_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.product_name_text)
        self.lineEdit_ProductName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ProductName.setObjectName("lineEdit_ProductName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ProductName)
        self.lineEdit_Price = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_Price.setObjectName("lineEdit_Price")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Price)
        self.price_text = QtWidgets.QLabel(self.formLayoutWidget)
        self.price_text.setObjectName("price_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.price_text)
        self.btn_save = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_save.setObjectName("btn_save")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_save)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.product_name_text.setText(_translate("MainWindow", "ProductName"))
        self.price_text.setText(_translate("MainWindow", "Price"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
