# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIcalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(945, 701)
        self.centralwidget = QtWidgets.QWidget(calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_num1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num1.setGeometry(QtCore.QRect(220, 180, 66, 18))
        self.lbl_num1.setObjectName("lbl_num1")
        self.lbl_num2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num2.setGeometry(QtCore.QRect(220, 230, 66, 18))
        self.lbl_num2.setObjectName("lbl_num2")
        self.txt_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(300, 180, 200, 32))
        self.txt_num1.setObjectName("txt_num1")
        self.txt_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(300, 230, 200, 32))
        self.txt_num2.setObjectName("txt_num2")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(300, 280, 81, 41))
        self.btn_add.setObjectName("btn_add")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(390, 280, 81, 41))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_mul = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mul.setGeometry(QtCore.QRect(480, 280, 81, 41))
        self.btn_mul.setObjectName("btn_mul")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(570, 280, 81, 41))
        self.btn_div.setObjectName("btn_div")
        self.lbl_res = QtWidgets.QLabel(self.centralwidget)
        self.lbl_res.setGeometry(QtCore.QRect(300, 350, 421, 31))
        self.lbl_res.setObjectName("lbl_res")
        calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 23))
        self.menubar.setObjectName("menubar")
        calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(calculator)
        self.statusbar.setObjectName("statusbar")
        calculator.setStatusBar(self.statusbar)

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "MainWindow"))
        self.lbl_num1.setText(_translate("calculator", "Sayı 1:"))
        self.lbl_num2.setText(_translate("calculator", "Sayı 2:"))
        self.btn_add.setText(_translate("calculator", "Topla"))
        self.btn_sub.setText(_translate("calculator", "Çıkar"))
        self.btn_mul.setText(_translate("calculator", "Çarp"))
        self.btn_div.setText(_translate("calculator", "Böl"))
        self.lbl_res.setText(_translate("calculator", "Sonuç:"))
